language: scala

scala:
  - 2.10.6
  - 2.12.3

jdk:
  - oraclejdk8

env:
  matrix:
    - TRAVIS_SBT_VERSION=1.0.0
    - TRAVIS_SBT_VERSION=0.13.16

script:
  - sbt ^^$TRAVIS_SBT_VERSION test scripted

matrix:
  exclude:
    - scala: 2.10.6
      env: TRAVIS_SBT_VERSION=1.0.0
    - scala: 2.12.3
      env: TRAVIS_SBT_VERSION=0.13.16
